---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cb-platform
  namespace: cb
  labels:
    app: cb-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb-platform
  template:
    metadata:
      labels:
        app: cb-platform
    spec:
      containers:
      - name: platform
        image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/platform
        env:
        - name: IS_TESTNET
          value: {{ quote .Values.is_testnet }}
        - name: BASE_URL
          value: {{ .Values.platform_hostname }}
        - name: BROWSER_BASE_URL
          value: {{ .Values.api_browser_base_url }}
        - name: PRIVATE_BASE_URL
          value: {{ .Values.api_base_url }}
        ports:
        - containerPort: 3000
        resources: {}
  strategy: {}