apiVersion: v1
kind: Service
metadata:
  labels:
    app: cb-corporate
  name: cb-corporate
  namespace: cb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cb-corporate
  sessionAffinity: None
  type: ClusterIP