apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cb-cert-manager-http01-issuer
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  name: cb-ingress-admin
spec:
  rules:
  - host: {{ .Values.admin_hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cb-admin
            port:
              number: 8088
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - {{ .Values.admin_hostname }}
    secretName: cb-ingress-cert-admin