---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cb-platform-rest-api
  namespace: cb
  labels:
    app: cb-platform-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb-platform-rest-api
  template:
    metadata:
      labels:
        app: cb-platform-rest-api
    spec:
      containers:
      - name: api
        image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/api
        env:
        - name: BASE_URL
          value: {{ .Values.platform_hostname }}
        - name: BSCSCAN_API
          valueFrom:
            secretKeyRef:
              name: cb-platform-external
              key: bscscan-api-key
        - name: REDIS_SERVER
          value: cb-platform-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cb-platform-redis
              key: redis-password
        - name: MAILCHIMP_LIST_ES
          value: "3373c90ede"
        - name: MAILCHIMP_LIST
          value: "922519c58b"
        - name: MAILCHIMP_API
          valueFrom:
            secretKeyRef:
              name: cb-platform-mailchimp
              key: api-key
        - name: EMAIL_SECRET
          valueFrom:
            secretKeyRef:
              name: cb-platform-smtp
              key: email-secret
        - name: SMTP_HOST
          value: "email-smtp.eu-west-1.amazonaws.com"
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: cb-platform-smtp
              key: smtp-user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: cb-platform-smtp
              key: smtp-password
        - name: SESSION_SECRET
          value: {{ .Values.api_session_secret }}
        - name: MYSQL_DATABASE
          value: cryptobirds
        - name: MYSQL_SERVER
          value: cb-platform-mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cb-platform-mysql
              key: mysql-root-password
        - name: MONGODB_CLUSTER
          valueFrom:
            secretKeyRef:
              name: cb-platform-mongo
              key: mongodb-cluster
        - name: MONGODB_DB
          valueFrom:
            secretKeyRef:
              name: cb-platform-mongo
              key: mongodb-db
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: cb-platform-mongo
              key: mongodb-user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cb-platform-mongo
              key: mongodb-password
        ports:
        - containerPort: 8088
        resources: {}
  strategy: {}