apiVersion: v1
kind: Service
metadata:
  labels:
    app: cb-platform-rest-api
  name: cb-platform-rest-api
  namespace: cb
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: cb-platform-rest-api
  sessionAffinity: None
  type: ClusterIP