apiVersion: batch/v1
kind: Job
metadata:
  name: delete-stable-mongo
spec:
  template:
    spec:
      containers:
      - name: bb-delete-stable-mongo
        image: 359744453235.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
        command: ["node", "scripts/delete-stable-mongo.js"]
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cb-platform-mysql
                key: mysql-root-password
          - name: MYSQL_SERVER
            value: cb-platform-mysql
          - name: MYSQL_DATABASE
            value: cryptobirds
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cb-platform-mysql
                key: mysql-root-password
          - name: MONGODB_CLUSTER
            valueFrom:
              secretKeyRef:
                name: cb-platform-mongo
                key: mongodb-cluster
          - name: MONGODB_DB
            valueFrom:
              secretKeyRef:
                name: cb-platform-mongo
                key: mongodb-db
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: cb-platform-mongo
                key: mongodb-user
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cb-platform-mongo
                key: mongodb-password
      restartPolicy: OnFailure