apiVersion: batch/v1
kind: Job
metadata:
  name: update-positions
spec:
  template:
    spec:
      containers:
      - name: bb-scores
        image: 647183375757.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
        command:
        - node
        - scripts/birdbrain.js
        - scores
        - -p
        env:
          - name: BROWSER_BASE_URL
            value: "https://platform.eks-dev.cryptobirds.com/api"
          - name: API_AUTH_EMAIL
            value: "noreply-api-user@cryptobirds.com"
          - name: API_AUTH_PASSWORD
            value: "**"
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cb-platform-mysql
                key: mysql-root-password
          - name: MYSQL_SERVER
            value: cb-platform-mysql
          - name: MYSQL_DATABASE
            value: cryptobirds
      restartPolicy: OnFailure
