apiVersion: batch/v1
kind: CronJob
metadata:
  name: 4chan-cronjob
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-4chan
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - 4chan
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: add-coingecko-coins-cronjob
  namespace: cb
spec:
  schedule: "0 0 * * 3"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-add-coingecko-coins
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - coingecko
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-cronjob
  namespace: cb
spec:
  schedule: "0 2 * * 3"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-github
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - github
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cb-github-token
                    key: github-token
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: twitter-cronjob
  namespace: cb
spec:
  schedule: "0 2 * * 4"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-twitter
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - twitter
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
              - name: TWITTER_CONSUMER_KEY
                valueFrom:
                  secretKeyRef:
                    name: cb-twitter-credentials-dev
                    key: cb-twitter-consumer-key
              - name: TWITTER_CONSUMER_SECRET
                valueFrom:
                  secretKeyRef:
                    name: cb-twitter-credentials-dev
                    key: cb-twitter-consumer-secret
              - name: TWITTER_BEARER_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cb-twitter-credentials-dev
                    key: cb-twitter-bearer-token
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: telegram-cronjob
  namespace: cb
spec:
  schedule: "0 12 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-telegram
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - telegram
            env:
              - name: TELEGRAM_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cb-telegram-credentials-dev
                    key: cb-telegram-token
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-cronjob
  namespace: cb
spec:
  schedule: "0 19 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-reddit
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - reddit
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-market-info-cronjob
  namespace: cb
spec:
  schedule: "0 21 * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-update-market-info
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - market
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scores-cronjob
  namespace: cb
spec:
  schedule: "0 20 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-scores
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - scores
            env:
              - name: BROWSER_BASE_URL
                value: {{ .Values.api_browser_base_url }}
              - name: API_AUTH_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: cb-api-user
                    key: api-auth-email
              - name: API_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-api-user
                    key: api-auth-password
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: copy-to-mongo-cronjob
  namespace: cb
spec:
  schedule: "0 21 * * 0" # it should run right after the scores job is completed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-copy-to-mongo
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/copy-to-mongo.js
            env:
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MONGODB_CLUSTER
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-cluster
              - name: MONGODB_DB
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-db
              - name: MONGODB_USER
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-user
              - name: MONGODB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-password
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: process-contests-cronjob
  namespace: cb
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-process-contests
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - process-contests
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-contest-statuses-cronjob
  namespace: cb
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-update-contest-statuses
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain
            command:
            - node
            - scripts/birdbrain.js
            - contest-status
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mysql
                    key: mysql-root-password
              - name: MYSQL_SERVER
                value: cb-platform-mysql
              - name: MYSQL_DATABASE
                value: cryptobirds
          restartPolicy: OnFailure