apiVersion: batch/v1
kind: CronJob
metadata:
  name: bb-python-cronjob
spec:
  schedule: "0 23 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb-python
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/birdbrain-python
            args: ["--mode", db]
            # volumeMounts:
            # - name: bbprogems-python
            #   mountPath: /data/results
            env:
              - name: MONGODB_USER
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-user
              - name: MONGODB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-password
              - name: MONGODB_CLUSTER
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-cluster
              - name: MONGODB_DB
                valueFrom:
                  secretKeyRef:
                    name: cb-platform-mongo
                    key: mongodb-db
          # volumes:
          # - name: bbprogems-python
          #   emptyDir: {}
          restartPolicy: OnFailure