apiVersion: batch/v1
kind: CronJob
metadata:
  name: certificator-job
  namespace: cb
spec:
  schedule: "0 21 * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: certificator
            image: {{ .Values.aws_account_id }}.dkr.ecr.eu-west-1.amazonaws.com/certificator
            env:
              - name: "API_AUTH_EMAIL"
                valueFrom:
                  secretKeyRef:
                    name: cb-certificator-secrets
                    key: api-auth-email
              - name: "API_AUTH_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: cb-certificator-secrets
                    key: api-auth-password
              - name: "WEB3J_CLIENT_ADDRESS"
                valueFrom:
                  secretKeyRef:
                    name: cb-certificator-secrets
                    key: web3j-client-address
              - name: "ETH_PRIVATE_KEY"
                valueFrom:
                  secretKeyRef:
                    name: cb-certificator-secrets
                    key: eth-private-key
              - name: "API_URL"
                value: http://cb-platform-rest-api:8088
              - name: "ETH_CONTRACT_ADDRESS"
                value: 0x184c52DC4b6F973EF3E951b283215190a537a69d
              - name: "ETH_TRANSACTION_VIEWER_URL"
                value: https://rinkeby.etherscan.io/tx/
          restartPolicy: OnFailure