aws_account_id: "359744453235"
images_bucket_name: "cb-dev-platform-images"
api_browser_base_url: "https://cryptobirds.com/api"
admin_hostname: "admin.eks-prod.cryptobirds.com"
api_hostname: "cryptobirds.com"
api_session_secret: "nnvoiiio49800fvnmppai2"
platform_hostname: "cryptobirds.com"
api_base_url: "http://cb-platform-rest-api:8088"
is_testnet: false
mysql:
  primary:
    extraEnvVars:
      - name: TZ
        value: "Europe/Madrid"
    configuration: |-
      [mysqld]
      default_authentication_plugin=mysql_native_password
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION

      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/lib/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid